### ISSUE TITLE
My Mod

### ISSUE THREAD

**Issue by GalaxyOnVR** [Octis13/Reposted-gorilla-tag-mods-qmod#1]
Grapple monkey is mine but you can keep it in there.

**Comment by Octis13** [comment]
Thanks, I appreciate it :)

**Comment by vskarson** [comment]
> Grapple monkey is mine but you can keep it in there.

no its not yours ;)

**Comment by GalaxyOnVR** [comment]
> > Grapple monkey is mine but you can keep it in there.
> 
> no its not yours ;)

Im saying its mine until the actual creator tells me its theres. im just waiting

**Comment by Octis13** [comment]
Oh yeah and galaxy if you know how do you use grapple monkey?
